name: Publish to NuGet

on:
  push:
    branches: [master]

jobs:
  publish:
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.NUGET_KEY }}
          nuget-version: 'latest'
      
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: navigate to workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: restore packages
        run: nuget restore DCRPUtils.sln
        
      - name: build solution
        run: msbuild.exe DCRPUtils.sln /p:configuration="Release"
        
      - name: pack & publish shared
        if: "contains(github.event.commits[0].message, 'shared'"
        run: |
          cd DiamondCrew.FiveM.Utils.Shared
          nuget pack -OutputFileNamesWithoutVersion
          nuget push DiamondCrew.FiveM.Utils.Shared.nupkg -Source https://api.nuget.org/v3/index.json

      - name: navigate to workspace
        run: cd $GITHUB_WORKSPACE

      - name: pack & publish client
        if: "contains(github.event.commits[0].message, 'client'"
        run: |
          cd DiamondCrew.FiveM.Utils.Client
          nuget pack -OutputFileNamesWithoutVersion
          nuget push DiamondCrew.FiveM.Utils.Client.nupkg -Source https://api.nuget.org/v3/index.json

      - name: navigate to workspace
        run: cd $GITHUB_WORKSPACE
    
      - name: pack & publish server
        if: "contains(github.event.commits[0].message, 'server'"
        run: |
          cd DiamondCrew.FiveM.Utils.Server
          nuget pack -OutputFileNamesWithoutVersion
          nuget push DiamondCrew.FiveM.Utils.Server.nupkg -Source https://api.nuget.org/v3/index.json