name: Publish to NuGet

on:
  push:
    branches: [master]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.NUGET_KEY }}
          nuget-version: 'latest'
      
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: navigate to workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: restore packages
        run: nuget restore DCRPUtils.sln
        
      - name: build solution
        run: msbuild.exe DCRPUtils.sln /p:configuration="Release"
        
      - name: pack client
        run: |
          cd DiamondCrew.FiveM.Utils.Client
          nuget pack -OutputFileNamesWithoutVersion -OutputDirectory ${{ env.GITHUB_WORKSPACE }}
      
      - name: publish client
        run: |
          nuget push ${{ env.GITHUB_WORKSPACE }}\DiamondCrew.FiveM.Utils.Client.nupkg -Source https://api.nuget.org/v3/index.json
    
      - name: pack server
        run: |
          cd DiamondCrew.FiveM.Utils.Server
          nuget pack -OutputFileNamesWithoutVersion -OutputDirectory ${{ env.GITHUB_WORKSPACE }}
        
      - name: publish server
        run: nuget push ${{ env.GITHUB_WORKSPACE }}\DiamondCrew.FiveM.Utils.Server.nupkg -Source https://api.nuget.org/v3/index.json